name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Streamlit Cloud
      uses: streamlit/streamlit-deploy-action@v1.0.0
      with:
        streamlit_app_root: "."
        streamlit_app_file: "app.py"
        streamlit_app_url: ${{ secrets.STREAMLIT_APP_URL }}
        streamlit_app_token: ${{ secrets.STREAMLIT_APP_TOKEN }}
